### ISSUE TITLE
Euler symbol

### ISSUE THREAD

**Issue by linuxrider** [Leedehai/typst-physics#18]
Does it make sense to add an abbreviation for the Euler constant `upright(e)` e.g. `eu`?
Background: elementary charge _`e`_ and Euler number `e` in nearby or same equation

**Comment by YDX-2147483647** [comment]
Honestly speaking, I do not think it should be included in _physica_.

- You can simply `#let eu = math.upright("e")` and write `$eu$`.
- Upright _e_ may not be a universal convention. [Wikipedia](https://en.wikipedia.org/wiki/E_(mathematical_constant)) uses the italic _e_, and the LaTeX package `physics` does not offer it.
- Besides, I think `eu` is too confusing. European Union, Euler's constant γ, …

**Comment by linuxrider** [comment]
- You are right. A  custom definition is easy. And this the way I am already using it.
- There is the standard [ISO 80000-2](https://en.wikipedia.org/wiki/ISO_80000-2) mentioned in https://en.wikipedia.org/wiki/Mathematical_notation with upright constants. But of course traditionally it is not used everywhere consequently.
I am coming from the field of chemistry where we adhere more or less to the IUPAC convention with upright constants.
- Regarding the abbreviation: This was only an example which came to mind first because I'm already using it.

Thanks for your work and feel free to close if this didn't change your mind.

**Comment by Leedehai** [comment]
Hi - I agree with the difficulty of deciding whether the upright form is the most universal, and naming it "eu" may conflate with others (especially, [Euler's constant](https://en.wikipedia.org/wiki/Euler's_constant)).

Giving it a longer and more descriptive name makes sense (`euler-symbol`?), but the benefits would be much less compared to just going with user-customized `#let eu = math.upright("e")`. The user-customized version is easier to type, and unambiguous (since users defined it themselves).

I'll close the issue for the moment, but thanks for opening this issue & letting me know your use cases!
